### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by Artiom-M** [Ribtoks/xpiks#117]
It is really minor but this is the only compile warning and it will be nice to fix:

In file included from moc_artworksrepository.cpp:9:0:
Models/artworksrepository.h: In copy constructor ‘Models::ArtworksRepository::ArtworksRepository(const Models::ArtworksRepository&)’:
Models/artworksrepository.h:42:9: warning: base class ‘class Models::AbstractListModel’ should be explicitly initialized in the copy constructor [-Wextra]
         ArtworksRepository(const ArtworksRepository &copy):

**Comment by Ribtoks** [comment]
Too bad I didn't get any warnings on OS X and Windows. Can you please check if there're no warnings now and close the issue then.

**Comment by Artiom-M** [comment]
Fixed now
