### ISSUE TITLE
Git master fails to build, breaks on hunspell

### ISSUE THREAD

**Issue by prokoudine** [Ribtoks/xpiks#184]
On clean clone of the master branch:

SpellCheck/spellcheckworker.cpp:32:55: fatal error: ../hunspell-1.3.3/src/hunspell/hunspell.hxx: No such file or directory
compilation terminated.

That said, I didn't generate Makefile via Qt Creator. I just used 'qmake-qt5 xpiks-qt.pro' command in CLI. I hope that was supposed to be good enough :)

**Comment by Ribtoks** [comment]
I didn't manage to update BUILD.md **YET**. Basically you need to download Hunspell http://hunspell.sourceforge.net/ from here and open project src/hunspell/hunspell.pro and build it. Afterwards, move library to the src/libs directory. And only afterwards you should build main project.

**Comment by Ribtoks** [comment]
You can see updated instructions in BUILD.md

**Comment by prokoudine** [comment]
So it won't build with hunspell dev headers already installed in the system?

**Comment by Ribtoks** [comment]
No. How would it know from Qt Creator you have Hunspell headers? The only way would be to write if-defs in the .pro file, but it will be not only platform-specific (for linux distro) but only distro-specific (as different distros have different path to development packages).

**Comment by prokoudine** [comment]
So I guess I'm basically requesting some sort of a build system like CMake (without knowing that I'm doing it :))

OK, let's stick to BUILD.md instructions for now. Thanks!

**Comment by Ribtoks** [comment]
No problem. Sorry didn't have time to write CMake file. Btw, pay attention you have to open `src/quazip/quazip/quazip.pro` not the `src/quazip/quazip.pro` - Updated build.md
