### ISSUE TITLE
Keyword suggestion UI : wrong position of click zone on the keyword

### ISSUE THREAD

**Issue by Artiom-M** [Ribtoks/xpiks#188]
On Linux.
The plus sign after the keyword name and the click zone are misaligned. I have to click on the last letters of the keyword for adding it.
I also noticed, that this sign changes the colour on hover, but it is almost invisible. It is a good hint, when you hover this sign and should be more visible. I think the dominant application colour (the kind of blue marine) would be a good candidate for it.

**Comment by Ribtoks** [comment]
I can confirm plus/close sign works flawlessly in OpenSUSE 13.2, Qt 5.5.1
I agree about need of a more explicit color, but I prefer my "modification color" which is used to indicate a change in several place though Xpiks, so I used it.

Can you confirm problem still persists? What Linux distro are you testing in?

**Comment by Artiom-M** [comment]
My Linux is Mint LMDE (Debian Edition). I will test it next week.

**Comment by Ribtoks** [comment]
Did you manage to confirm the issue?

**Comment by Artiom-M** [comment]
This is fixed now in 1.1.4.

**Comment by Ribtoks** [comment]
Then I will close the issue.
