### ISSUE TITLE
Loading Hunspell dictionaries from system directory on Linux

### ISSUE THREAD

**Issue by Ribtoks** [Ribtoks/xpiks#218]
At the moment Linux build is outdated because it's not the right way to include hunspell dicts with the application. So it should be possible to load dicts from system directory.

**Comment by Artiom-M** [comment]
I have implemented it, but the best way to manage dictionaries is to have a setting with dictionary path filled with OS dependent default value. On different distributions dictionary directories can be different, it's tricky to auto-detect them and users could have their own dictionaries installed to some custom path.

**Comment by Ribtoks** [comment]
Xpiks needs just two dictionaries at the moment. And it is assumed that they are present. Can it be guaranteed with .deb that dictionaries will be installed?

`hunspell -D` outputs paths to the dictionaries. Maybe there's a way to do this with libhunspell as well..

**Comment by Artiom-M** [comment]
Surely we can put some dictionaries to dependencies. Maybe like recommended packages. 
I've seen you use en_US. What is the second?

`hunspell -D` will print a list of paths it was compiled with. These are places where most likely dictionaries can be found. Hunspell and dictionaries are separate projects and location can vary a lot between distributions and user preferences. So for more flexibility this path should be user changeable.

**Comment by Artiom-M** [comment]
This to say, there is no standard way to find installed dictionaries in the system like it is possible for  libraries for example.

**Comment by Ribtoks** [comment]
You can find a guide how to add a new setting in the [Wiki of Xpiks](https://github.com/Ribtoks/xpiks/wiki/How-to-add-a-new-Setting-to-Xpiks). Also I would suggest you to hardcode 4-5 possible system standard paths to dictionaries as well as to user's home dictionaries directory (of course, under LINUX ifdef).

Files which are needed are _.aff_ and _.dic_ parts of _en_US_ dictionary.

in SettingsWindow.qml perfect place to add such a path would be **External** tab.

**Comment by Artiom-M** [comment]
I followed Wiki, it works. But I need to restart in order the setting takes effect. How to apply it in run time?

**Comment by Ribtoks** [comment]
You will have to modify SpellCheckerService and SpellCheckerWorker a bit.
1. Introduce volatile bool private member of _SpellCheckerService_ smth like _m_WorkerRestartRequired_. Initialize with false in constructor.
2. Introduce method _restartWorker()_ where you will set restartRequired to true and stopWorker();
3. Create a new slot in the Service that will handle _destroyed()_ signal of Worker (and connect signal of worker with this slot in the _startWorker()_ method)
4. In the _onWorkerDestroyed()_ slot check if _restartRequired_ and then create new instance of worker and call startWorker().

**Comment by Ribtoks** [comment]
If you have some issues with the implementation of worker restart, you can leave it to me. Just commit your changes and create pull request.
