### ISSUE TITLE
Shadow upgrade system

### ISSUE THREAD

**Issue by Ribtoks** [Ribtoks/xpiks#220]
Implement shadow upgrader which will force upgrade on the startup

**Comment by Ribtoks** [comment]
Mac stuff will not work since Sparkle want's the package to be signed with iStore Developer certificate (or some other)

**Comment by Artiom-M** [comment]
Will not work for linux as well since needs root in order to install something

**Comment by Ribtoks** [comment]
@Artiom-M Yes, it won't work anyway in the way I wanted it to work. So for Windows it will be ordinary custom updater and for OS X it will be just launch of another package *.dmg (so user will do it himself). For Linux it's will finally lead to creating a repository.

**Comment by Ribtoks** [comment]
https://github.com/Ribtoks/ministaller/releases/tag/v0.1-alpha
