### ISSUE TITLE
Telemetry have to be optional with expicit agreement request

### ISSUE THREAD

**Issue by Artiom-M** [Ribtoks/xpiks#227]
Telemetry feature you added recently is a collection of user's activity so it is illegal in EU (and US I think) to do it without explicit user agreement. I think you have noticed recently Google asked you for this kind of permission - after several millions of fines payed to EU ;).

**Comment by Ribtoks** [comment]
There is an agreement. Launch Xpiks and it will explicitly ask you about permissions.

**Comment by Artiom-M** [comment]
I launched it many times. It didn't ask. I didn't see any notions of telemetry : settings, about... Where can I turn it off?

**Comment by Ribtoks** [comment]
Artiom, when you open Release build it asks if you agree to the Terms and Conditions. If you do not see it either you've already gave your consent or you launched Debug build. I know there's no bug there and "Terms and Conditions" window is being shown for at least 1 time. If you don't give your consent Xpiks clothes. 

You can't turn it off in the Release build. You can only recompile Xpiks without it.

**Comment by Artiom-M** [comment]
So this should be terms_and_conditions.txt file. I am still working on distribution and usage of two text files you added.
This means you refuse the use of Xpiks without collection of statistics. Why this politics?

**Comment by Ribtoks** [comment]
Yes it means absolutely what you've stated. At this point I'm very interested in daily users count and distribution of Xpiks features usage. "Telemetry" just sends enums with feature code. No more sophisticated "telemetry" is planned in future.

**Comment by Artiom-M** [comment]
It is against spirit of free software to create hidden functions like this. So it should be or explicitly announced (not just few words in the agreement hidden behind the scroll) or just stay an option that can be on by default. I think most of the users will not go and uncheck this option. If you want to hide it away from the first glance you can put it to some kind of "advanced options" tab, which can be activated by some "show advanced options " checkbox. By the way dictionary path option can be on this advanced tab as well. Default auto-detection  looks to work well and this option is mostly a quick fix feature for some users in trouble. And even Windows users could like the ability to use their dictionary in place of supplied one.

**Comment by Ribtoks** [comment]
"Under the ShowAdvanceOptions in Advanced Tab" where average user will not be able to find it? This is hiding. I just didn't give the ability to modify it except of recompilation.

Ok, I will leave it (but in the Security tab), but disabling of basic telemetry will last only certain amount of time. Afterwards it will get back on automatically. Please, do not send pull requests that drastically change this behavior. 

I've added it there for a reason but not my pleasure. I need it enabled. Users who will be able to go through the BUILD.md guide and recompile Xpiks without it can enjoy their builds of course.

**Comment by Artiom-M** [comment]
The Advanced tab is not for hiding this option. This to get it off the first sight. I am strictly against any hidden options affecting user's privacy. An average user will not go through all "Advanced" options and will not disable anything he don't feel he need to disable. I can propose that telemetry service sends the last message when user disables this option. It will be interesting to know how many users will disable it.

**Comment by Ribtoks** [comment]
Yes, it's a good idea to send this "Disable" message, thank you.
