### ISSUE TITLE
Ошибка импорта изображений: OS X 10.10.3 (15D21) - XPicks 1.1

### ISSUE THREAD

**Issue by mastaka** [Ribtoks/xpiks#254]
При импорте папки (либо единичных изображений) в которой находятся файлы (EPS + JPG) с прописанными в них через Adobe Bridge метадатами, импорт завершается с ошибкой — превью отображается, но данные отсутствуют.

Скриншоты:
https://monosnap.com/file/i1OlM7RNcJgR5hgcwe345zgRsgAz3G
https://monosnap.com/file/wNz4qwVOwHHaciPEgdKgFMQABuagaN

Лог: https://drive.google.com/file/d/0B0ttfjS23eBMY0VKakRaeUNzbm8/view?usp=sharing

**Comment by Ribtoks** [comment]
Вы не установили Exiftool. http://owl.phy.queensu.ca/%7Ephil/exiftool/
На странице загрузки Xpiks (http://ribtoks.github.io/xpiks/downloads/) написано жырным шрифтом, что надо установить Exiftool. К сожалению, очень многие пользователи не читают. Я постараюсь что-нибудь придумать в следующих версиях Xpiks.

**Comment by mastaka** [comment]
Нет, Exiftool (v 10.11) я инсталлировал первым делом, еще до установки Xpiks
https://monosnap.com/file/8wGLIM8dPGonS9Pedw3iFIt0T8vb6F

**Comment by Ribtoks** [comment]
Тогда Xpiks не может найти его у вас. В Settings -> External можно задать прямой путь к exiftool.
Попробуйте поискать в `/usr/bin/exiftool` или `/usr/local/bin/exiftool` или посмотрите, куда пакет Exiftool установил `exiftool`

**Comment by mastaka** [comment]
Exiftool инсталлируется в `/usr/local/bin/exiftool`, а не по пути `(/usr/bin/exiftool)` указанном в настройках по умолчанию: https://monosnap.com/file/1m54ypK0MNQFFQSkUA0mylrboro3to
После изменения адреса ошибка исчезла, данные читаются. Спасибо

**Comment by Ribtoks** [comment]
У меня в OS X 10.10.5 Exiftool инсталируеться в /usr/bin/exiftool. Я напишу потом autodiscovery.

**Comment by mastaka** [comment]
Думаю, что это может быть связано с новыми методами обеспечения безопасности (SIP?) в El Capitan

**Comment by Ribtoks** [comment]
Хз, возможно.
