### ISSUE TITLE
Ability to arrange keywords one by one and in batch.

### ISSUE THREAD

**Issue by sigma3d** [ribtoks/xpiks#270]
Hi there,

Is it possible to add arranging keywords with simple drag and drop method with batch edit capability.

Thanks.

**Comment by Ribtoks** [comment]
Hi
There's a Plain Text Edit where you can change order of keywords. Implementation of drag'n'drop of keywords is not in priority at the moment.

**Comment by ribtoks** [comment]
Need to implement this at least for single-editing mode..
