### ISSUE TITLE
Multiple paste function

### ISSUE THREAD

**Issue by guvend** [Ribtoks/xpiks#293]
On 1.2 i can be able to paste keywords to multiple images. On 1.3 seems its gone.
Multiple description paste function would be nice too.

**Comment by Ribtoks** [comment]
Yes, in 1.3 it's gone and it will not get back.
There would be another functionality with ability to quickly copy and paste title/description/keywords in Xpiks 1.4.

Until then please use Multiple Edit functionality (and with help of "Assign from selected" button).

**Comment by guvend** [comment]
Sorry for asking but how do i do that?

**Comment by Ribtoks** [comment]
It's covered in this video https://vimeo.com/155296801
(To paste keywords to multiple items, select them, press "Edit", uncheck Description and Title, check "Only append new keywords")

also you can use "Assign from selected" to quickly transfer metadata from one item to many in the same dialog.
