### ISSUE TITLE
Implement Recent Files model and menu entry

### ISSUE THREAD

**Issue by Ribtoks** [Ribtoks/xpiks#319]
Refactor `RecentDirectoriesModel` into a base class `RecentItemsModel` and inherit `RecentDirectoriesModel` and `RecentFilesModel`. Implement menu entry just like recent directories is implemented. Push into recent files model from `AddArtworksCommand::execute()`. Recent Files Model should hold up to 10 recent files (against 5 items in the Recent Directories Model).

**Comment by gnidorah** [comment]
Working on this
