### ISSUE TITLE
Copy to quickbuffer from keywords suggestion

### ISSUE THREAD

**Issue by Ribtoks** [Ribtoks/xpiks#367]
Right-click menu for the suggested image with copy to quickbuffer action which will copy title/description/keywords.

This requires reading Shutterstock/Fotolia/iStock Microstock API documentation of how to get Title and Description additionally to Keywords. Requires patching of all `*QueryEngine` classes in `Suggestion/` directory.

**Comment by gnidorah** [comment]
Working on it

**Comment by Ribtoks** [comment]
@gnidorah 

Shutterstock API https://developers.shutterstock.com/api/v2
Fotolia API https://us.fotolia.com/Services/API/Rest/Documentation#
iStock/Getty is not public

**Comment by gnidorah** [comment]
@Ribtoks Thank you!

**Comment by Ribtoks** [comment]
@gnidorah My pleasure. I've updated link to Getty's page. Good luck.
