### ISSUE TITLE
Move Qt settings to custom json file

### ISSUE THREAD

**Issue by Ribtoks** [Ribtoks/xpiks#376]
Refactor use of all Qt's settings to json file in the appdata directory. 

- Loading/Saving code should be only changed inside SettingsModel class, introducing `camelCase` names for json keys accordingly to the old property names. 
- There should be a different config for release and debug settings (like `debug_settings.json` and `settings.json`
- This touches a lot of code in UI as well (all uses of `appSettings` in the UI code should be refactored to usual usage of `settingsModel` which is already present there) and old stuff should be removed
- `constants.h` should contain new json keys instead of old uppercase keys
- Serialized data (like recent menu entries, microstocks credentials etc.) should be serialized as base64 string, QByteArray via QVariant or smth like that - as raw binary data

**Comment by gnidorah** [comment]
Working on it
