### ISSUE TITLE
Setting for turning off filtering based on path

### ISSUE THREAD

**Issue by Ribtoks** [Ribtoks/xpiks#377]
Currently filter field in the `MainGrid.qml` supports filtering by a whole bunch of data (title, description, keywords, reserved words, filepath etc.). This uses `Helpers::hasSearchMatch()` API which filters based on flags and search term.

This task is to make use of a `SearchFlags::Filepath` flag optional by creating a new Setting in the `SettingsWindow.qml` Behavior Tab with string "Search by path" as well as a field in `SettingsModel`  (https://github.com/Ribtoks/xpiks/wiki/How-to-add-a-new-Setting-to-Xpiks) and provide that flag in `FilteredArtItemsProxyModel::filterAcceptsRow()` as parameter for `Helpers::containsPartsSearch()` method.

**Comment by gnidorah** [comment]
Taking this
