### ISSUE TITLE
Building from source on Linux step-by-step

### ISSUE THREAD

**Issue by spot62** [Ribtoks/xpiks#378]
***Building from source on Linux step-by-step***
1) prepare system:
for Debian & etc:
   ...
for Fedora & etc:
   sudo dnf install curl-devel hunspell-devel quazip-devel zlib-devel exiv2-devel

2) prepare source:
   git submodule init
   git submodule update --recursive
   mv src/tiny-aes/aes.c src/tiny-aes/aes.cpp

3) build libs:  
   cd src/libs
   qmake-qt5 ../cpp-libface/libface-project/libface.pro
   make
   qmake-qt5 ../ssdll/src/ssdll/ssdll.pro
   make
   rm -f *.o Makefile
   cd ../..

3) build app:   
   mkdir build
   cd build
   qmake-qt5 ../src/xpiks-qt/xpiks-qt.pro
   make

4) run app:
   $ LD_LIBRARY_PATH=../src/libs/ ./xpiks-qt

**Comment by Ribtoks** [comment]
Hi

What is this issue about?

If you would like this to be included in the build instructions, you're welcome to contribute to BUILD.md file via pull request

**Comment by gnidorah** [comment]
@spot62 Things are simpler, if you just use Qt Creator. And considering that this project has a lot of GUI, you would like to have Qt Creator for design tasks anyway.

**Comment by spot62** [comment]
gnidorah, a open-source project must be builded by one click, imho, this is important
sorry, forget it

**Comment by Ribtoks** [comment]
@spot62 Script like yours is in .travis.yml file (https://github.com/Ribtoks/xpiks/blob/master/.travis.yml) so if you want to build it with 1 click (read 1 script) - there it is.

**Comment by spot62** [comment]
Ribtoks, ok, thank you
