### ISSUE TITLE
openSUSE package requires libhunspell-1.3 which is no longer provided in Tumbleweed repositories

### ISSUE THREAD

**Issue by tapwag** [Ribtoks/xpiks#420]
Hello everyone,

I would like to let you know that one dependency of "xpiks" has changed in latest openSUSE. I am using a rolling release version called "Tumbleweed" and had to install the following dependencies manually when trying to install the .rpm package.

zypper install libquazip1 
zypper install libqt5-qtgraphicaleffects 

However, the following dependency fails and libhunspell is now at a later version:

rpm -i Downloads/xpiks-1.4-1.x86_64.rpm 
error: Failed dependencies:
	libhunspell-1.3.so.0()(64bit) is needed by xpiks-1.4-1.x86_64

# zypper install libhunspell-1_
libhunspell-1_5-0        libhunspell-1_6-0        libhunspell-1_6-0-32bit  

Is it possible to update the rpm spec-file and rebuild the package?

For building packages and creating a repository the following service might become handy:
https://build.opensuse.org/

Have a good day,

Maik

**Comment by Ribtoks** [comment]
Hello Maik

Thank you very much for the info. Will fix for 1.5 release.

**Comment by Ribtoks** [comment]
@tapwag Hi. Can you please try AppImage which can be download from the Download page on a website or in the GitHub Releases? If it works for you, may I close the issue?

**Comment by tapwag** [comment]
Hello, thanks for providing this. I looks like an interesting approach which works fine on my openSUSE system. 

In short: Yes, you can close it as fixed as far as I am concerned.
