### ISSUE TITLE
DEVICE_PIXEL_RATIO Warning

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#437]
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
QT_SCREEN_SCALE_FACTORS to set per-screen factors.
QT_SCALE_FACTOR to set the application global scale factor.

Need to investigate and fix `main.cpp`

**Comment by moukhtar-b** [comment]
hi 

the solution is

`export QT_AUTO_SCREEN_SCALE_FACTOR=1  `

**Comment by ribtoks** [comment]
Hi @moukhtar-b 

Thanks, this is exactly what Qt warning says.
