### ISSUE TITLE
Remember suggestion media type between sessions

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#451]
Currently Photos/Vectors dropdown selected value is not saved between session neither of Suggest window nor between sessions of Xpiks.

Inherit Keywords Suggestor from `StatefulEntity`, add proper initialization and saving of states. Save selected index to state when it changes. (read more about states here https://github.com/ribtoks/xpiks/wiki/How-to-save-state-of-entity)

**Comment by RostaTasha** [comment]
In progress

**Comment by ribtoks** [comment]
Done in master.
