### ISSUE TITLE
Directory filter applied when directory removing undone

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#466]
If you remove a directory clicking a "cross" on the right and immediately afterwards you press "Undo", the directory is restored but it is selected and applied as a filter.

Steps to reproduce:

1. Add files
2. Click "remove" for a directory on the left
3. Click "Undo" link
4. The result: directory is restored and "selected" as a filter
[expected behavior] directory is not selected as a filter

Related #366
Root cause in #151

**Comment by Ribtoks** [comment]
@NataAb @RostaTasha I suppose this is yours
