### ISSUE TITLE
Unable to remove directories one by one

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#467]
When removing the directories (> 1) one by one clicking on a "cross" icon, the last directory stays forever.

Steps to reproduce:

1. Add several files from 2 different directories
2. Remove first directory (- it's files are removed and directory is removed)
3. Remove second directory
4. [Actual behavior] Files are removed but the directory stays there
[expected behavior] the directory is removed with files

The problem is that `m_DirectoryIdToIndex` is not updated when you remove directories so the code which removes a directory can corrupt memory in method `ArtworksRepository::removeFile()`.

How to fix:

1. **IMPORTANT** First of all add some failing tests for this case in core tests for artworks repository - adding 1by1 and removing 1by1 for the case of 1 dir and > 1 dir

2. Fix `ArtworksRepository::cleanupEmptyDirectories()` method and any other which removes items from `m_DirectoriesList` in the `ArtworksRepository`

Related #366 
Versions 1.4.2 and below not affected.

**Comment by Ribtoks** [comment]
@NataAb @RostaTasha I'm afraid this is yours as well

**Comment by ribtoks** [comment]
Fixed in f1cae82b
