### ISSUE TITLE
Show dialog with Warnings in the end of debug session

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#488]
Motivation for this task is to help developer (me) to detect new warnings that are introduced by some inconsistency (mainly in the UI).

This should be a separate UI application in the `src/` directory (like Recoverty). Main purpose of this application is to receive a path to the logfile as a single command-line parameter and analyze this logfile. Analysis means that this application will filter out loglines of type "Warning" and "Critical" and will visualize these loglines + few lines before + few lines after. Application will use for visualization ready control which is `LogsDialog.qml` in Xpiks and ready `logshighlighter.cpp` for highlighting. The only thing this app will do is given the path to loglines, it will create a squeezed output of warnings and show it in the UI. If there're no warnings, the application will just exit.

In it's turn, Xpiks only in Debug mode before exit will start this application providing it path to current logfile. The application will build itself like Recoverty so Xpiks will know where to start it from.

**Comment by velmafia** [comment]
@ribtoks: according to your email and your idea presented there, I will do this task using https://github.com/ribtoks/xpiks-logs-viewer
