### ISSUE TITLE
Copy mode is inactive in Edit window, if keyword have spelling error

### ISSUE THREAD

**Issue by velmafia** [ribtoks/xpiks#520]
_Copy_ mode is inactive in Edit window, if keyword have spelling error, see attached screenshot.
If all keyword is correct, the _Fix spelling_ option is changed to _Copy_. 

OK, I know the best solution is fix spelling, and add new worlds to dictionary, but sometime this "wrong keyword" is town/vilage/mountain name, and I don't want add this words to dictionary.

![xpiks-copy](https://user-images.githubusercontent.com/5277222/34893225-9484a470-f7dc-11e7-8c77-85d5f9fab059.jpeg)

aloha
Kamil

**Comment by ribtoks** [comment]
@velmafia no, it's not the best solution to fix spelling. It's a bug that copying is disabled. I'm fixing it right now. Thanks for reporting.
