### ISSUE TITLE
Xpiks AppImage fails to run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [ribtoks/xpiks#543]
Fails with:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/d67faaec2c80091dd3b748746ffec52f0e83d92f/database/Xpiks/screenshot.png)

Please compile on Ubuntu 14.04.

References:
* https://github.com/AppImage/appimage.github.io/pull/428
* https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by ribtoks** [comment]
Thanks for reporting that!
To my knowledge I have no users who want use it on 14.04. So unless they will show up my current plan is just to wait until 14.04 will stop being the "oldest LTS" in early 2019.

**Comment by ribtoks** [comment]
Closing as stale
