### ISSUE TITLE
Russian localization is too verbose in some places

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#544]
Some users reported this pics:

![image](https://user-images.githubusercontent.com/505555/36998444-9def2d3e-20c5-11e8-9602-ad528ec1eabd.png)

![image](https://user-images.githubusercontent.com/505555/36998463-afc1a28a-20c5-11e8-9f4a-07f20f201b86.png)

**Comment by RostaTasha** [comment]
![image](https://user-images.githubusercontent.com/13381541/37625418-e87fdb60-2bdc-11e8-831e-5c1ee89d33a0.png)

**Comment by RostaTasha** [comment]
![image](https://user-images.githubusercontent.com/13381541/37625468-17059894-2bdd-11e8-8e6a-9555cc203138.png)

**Comment by RostaTasha** [comment]
Suggested translations in the crowdin

**Comment by ribtoks** [comment]
@RostaTasha Thanks, confirmed!
