### ISSUE TITLE
Recoverty unusable within AppImage

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#569]
`Recoverty` is a trivial helper app which restarts Xpiks in case the latter crashes. This is implemented via intercepting various signals/handlers using [chillout](https://github.com/ribtoks/chillout) library which in the event of crash shows friendly crash picture and restart button.

When AppImage starts it creates temporary directory which renders `Recovery` logic useless since temp directory is removed when Xpiks crashes hence Recovery cannot be started from nowhere + even if Recoverty would start, it will fail to restart Xpiks since it's path is invalid at that moment.

**Comment by TheAssassin** [comment]
@ribtoks you either need to "keep the AppImage alive", i.e., put some crash handling into your AppImage (by writing your own AppRun script that takes care of this), or you need this external tool to be aware of AppImage (i.e., re-run the AppImage and not the crashed application). I don't know how to properly implement the latter, though, as there's no really good way to resolve the AppImage's location from the mount directory (it'd be possible to register AppImages in some in-memory thingy to make external apps aware of it, though).

AppImageLauncher could also provide such functionality, as it manages the AppImages' execution.

**Comment by ribtoks** [comment]
@TheAssassin Thanks for the detailed response! Currently it seems to be a bigger challenge to make this "restarter" start than to find path to AppImage for me. The only silly thing that comes to my mind is to check return code of main app and sleep in case it's not `0`..

**Comment by TheAssassin** [comment]
I have to say I have no clue how this project you mentioned works. Do you have a link?

**Comment by probonopd** [comment]
The AppImage exists when AppRun exits. If you want to restart the payload, then you need to make sure that AppRun doesn't exit prematurely.

**Comment by ribtoks** [comment]
@TheAssassin This project is a part of Xpiks. The logic is following:
1. in `main()` Xpiks installs crash handler that prints stacktraces to logs, executes `recoverty /path/to/main/exe` command and exits
2. If Xpiks crashes, recoverty shows up and it has 1 button "Restart" that launches `/path/to/main/exe` command and exits
3. Profit

In case above this is not enough, this is raw code:

* [Recoverty code](https://github.com/ribtoks/xpiks/tree/master/src/recoverty)
* [initCrashHandler() code in Xpiks](https://github.com/ribtoks/xpiks/blob/master/src/xpiks-qt/main.cpp#L127)

**Comment by TheAssassin** [comment]
@ribtoks that's an easy fix. Don't use `startDetached()`, but some variant of `exec()`. That way, the current process is replaced with the new xpiks process, and the AppImage will remain to be mounted.

**Comment by ribtoks** [comment]
@TheAssassin Hm, indeed, will try with `exec()`.. Thanks for your help!

**Comment by ribtoks** [comment]
Fixed in master for 1.5.2 release.

**Comment by TheAssassin** [comment]
Cool. I assumed using `exec()` worked?

**Comment by ribtoks** [comment]
@TheAssassin Worked like a charm once I figured out I should duplicate app name/path as first argument (which is kinda obvious but I hoped `execl()` would do it for me and wondered why it didn't work). Thanks!
