### ISSUE TITLE
Use cppclean to check code in CI

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#575]
https://github.com/myint/cppclean

**Comment by velmafia** [comment]
I will do this, please assign me to this task.

**Comment by ribtoks** [comment]
@velmafia I cannot assign you in terms of GitHub because of https://github.com/isaacs/github/issues/100 (GitHub does not allow assigning users without push permissions to issues). But you we can assume you're "assigned" if that's ok for now.

**Comment by ribtoks** [comment]
@velmafia btw, this issue should be read as following:
1. run `cppclean` locally, find all bad places in Xpiks and fix odd includes
2. automate step (1) to run in CI

**Comment by velmafia** [comment]
What about false-positive `cppclean` output? For example here:

> src/xpiks-qt/Artworks/artworkelement.h:17: 'artworkmetadata.h' does not need to be #included; use a forward declaration instead
> src/xpiks-qt/Artworks/basickeywordsmodelimpl.h:23: '../Common/flags.h' does not need to be #442 

Unfortunately `cppclean` [don't support suppression mechanism](https://github.com/myint/cppclean/blob/master/cpp/find_warnings.py). I can exclude this whole file from check, but this is (IMO) poor solution.

-----------------
I close this issue using another way:
1. Create a script to run cppclean
2. Add this script to CI
3. For all directory in src:
  3a. Add directory to check in script
  3b. Fix warning locally 
4. Create pull request for stand-alone working batch with "green CI".

This will be more CI approach, and I hate big review with several hundred changed files

**Comment by ribtoks** [comment]
@velmafia  I don't see a problem with `artworkelement.h` tool's command is fair: we can forward-declare `Artworks::ArtworkMetadata` (e.g. as done in file `templatedcommand.h`).

`basickeywordsmodelimpl.h` probably doesn't like `flags.h` because `iartworkmetadata.h` includes them as well.

As a general answer: if you redirect cppclean output to a file, you can `sed` out particular entries from there.

CI comment - sure, it's definitely "more CI".

**Comment by velmafia** [comment]
problem with `artworkelement.h` is here:

> size_t getOriginalIndex() const { return **m_Artwork->getLastKnownIndex();** }


In `basickeywordsmodelimpl.h` cppclean mark `iartworkmetadata.h` as unused (because it's), also `../Common/flags.h` is mark as not needed - but this is false-positive warning.

-----------------------

[Here](https://travis-ci.org/velmafia/xpiks/jobs/433227258) is my draft for this task with this 2 false-positive warning.

**Comment by velmafia** [comment]
I made some test with `cppclean`, and:
- it's don't analyse `<>` include, I can add `#include <whatever>` and `cppclean` don't print warning. So everything included this way (std, qt, and xpiks header are not cleaned).
- it's crash or `parsing error` quite often.
- it's prints a lots of false-positive warning.

I think this tool it's ok when you want use it's locally and interpret warnings by yourself. But for CI job it's still too immature.

Most (if not all) things that `cppclean` does, can be done by `cppcheck` (with `--enable=all`) and [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use) (and I trust them more).
I can clean-up code locally using this tools, but iwyu is really heavy (it's need compiling code, ant it's take much longer than normal compilation), so also add it to CI?

**Comment by ribtoks** [comment]
@velmafia yes you can, thanks. I didn't use cppclean a lot, just found it to be nice tool that probably could do what I want for xpiks. If it is not upto our expectations, of course we can dismiss it.

**Comment by ribtoks** [comment]
Closing as questionable.
