### ISSUE TITLE
Undo from Single Artwork Edit View

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#610]
Currently if you insert preset or paste from quickbuffer in the single artwork editing view, you cannot undo the action. Create a similar "Undo" link (as in the Main Grid View) that disappears after the timeout that is capable of undoing.

**Comment by velmafia** [comment]
I grab this task.

**Comment by ribtoks** [comment]
Investigation finished with the result "significant refactoring required" because `ArtworkProxyBase` uses `IMetadataOperator` which is incompatible with commands that expect `ArtworkMetadata`.
