### ISSUE TITLE
Add option to Open artwork with default application

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#620]
Add option "Open" next to "Show in folder" in the artwork's context menu that will do `open` on macOS, start process with filename on Windows and do smth like `xdg-open` on Linux

**Comment by velmafia** [comment]
@ribtoks: I think `MenuSeparator` will improve readability, what do you think?

![separator-reorder](https://user-images.githubusercontent.com/5277222/60307780-4a034700-9946-11e9-84d4-01f418c5213e.jpeg)

**Comment by ribtoks** [comment]
@velmafia Sure, looks OK.

**Comment by ribtoks** [comment]
It did not work on Windows (it works only from `cmd` if you execute it like `cmd \C start /path/to/file`. I fixed in cd4a6179. Need to check in other systems.

**Comment by velmafia** [comment]
For `linux` and `macos` it's works, I tested this OS.
