### ISSUE TITLE
Suggestion search always return 0 items: "Invalid access token"

### ISSUE THREAD

**Issue by hybroid** [ribtoks/xpiks#634]
Suggestion search don't work.

Log cut:
`23:51:01.659 info T#29421 Models::ArtItemsModel::initSuggestion - item 0
23:51:01.659 debug T#29421 Suggestion::KeywordsSuggestor::setExistingKeywords - #
23:51:01.659 debug T#29421 launchDialog - Opening dialog ../Dialogs/KeywordsSuggestion.qml ...
23:51:01.670 info T#29421 launchDialog - Opened dialog ../Dialogs/KeywordsSuggestion.qml. Opened dialogs count is 1
23:51:07.454 info T#29421 Suggestion::KeywordsSuggestor::searchArtworks - [ "village" ], search type: 0
23:51:07.454 info T#29421 Microstocks::ShutterstockAPIClient::search - "village"
23:51:07.455 debug T#29421 Connectivity::RequestsService::sendRequest - #
23:51:07.455 debug T#29421 Connectivity::TelemetryService::reportAction - Telemetry disabled
23:51:07.455 info T#29430 Connectivity::RequestsWorker::sendRequest - Request: "https://api.shutterstock.com/v2/images/search?language=en&view=full&per_page=100&page=1&sort=popular&query=village"
23:51:07.456 debug T#29430 Connectivity::fillProxySettings - Using proxy: ""
23:51:07.725 info T#29430 Connectivity::SimpleCurlRequest::doRequest - 34 bytes received
23:51:07.727 warning T#29430 Suggestion::ShutterstockSuggestionResults::parseResponse - [data] element is not an array in "{\n    \"message\": \"Invalid access token\"\n}\n"
23:51:07.728 info T#29421 Suggestion::KeywordsSuggestor::setSuggestedArtworks - 0 item(s)
23:51:07.728 info T#29421 Suggestion::KeywordsSuggestor::setSuggestedArtworks - With sequential loading: true
`
Search URL for Shutterstock return "Invalid access token".
OS: Arch Linux
Xpiks 1.5.2, release build. Native build, PKGBUILD file of package was here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xpiks
PS: AppImage distribution from this don't work: library conflict and sigfault with 3rd libraries.

**Comment by ribtoks** [comment]
@hybroid unfortunately some custom builds in AUR will not have proper access keys, as logs are saying. Can't help you with this. We can try to debug AppImage though and see what causes the conflict.

**Comment by hybroid** [comment]
It's my build in AUR :)
I make them from git sources (tag "v1.5.2"). Sources contains access keys?

For AppImage I create new issue.

**Comment by ribtoks** [comment]
@hybroid git source code does not have valid access keys to any microstock websites. Any Linux packages other than AppImage and/or flatpak are discouraged from use.
