### ISSUE TITLE
AppImage doen't work on Arch Linux: missing libs

### ISSUE THREAD

**Issue by hybroid** [ribtoks/xpiks#635]
I'm doing:
`$ ./Xpiks-v1.5.2-x86_64.AppImage --appimage-extract`

`$ cd squashfs-root/`

`$ ./AppRun`
`./AppRun: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory`

Ok. Installing libidn with other version:
`$ sudo pacman -S libidn11`
`./AppRun: relocation error: /usr/lib/libk5crypto.so.3: symbol k5_os_mutex_destroy version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference`

`$ pacman -Qo /usr/lib/libk5crypto.so.3
/usr/lib/libk5crypto.so.3 is owned by krb5 1.16.1-1`

Ok. I copy my libkrb5support.so.0 in ./libs (suddenly lucky? :) ):
`$  mv lib/libkrb5support.so.0{,.bak}`
`$ cp /usr/lib/libkrb5support.so.0 ./lib`
`$ ./AppRun`
`QFSFileEngine::open: No file name specified`
`Aborted (core dumped)`

Maybe need to add libk5crypto.so.3 to the AppImage package?

**Comment by ribtoks** [comment]
Can you please check the stacktrace in the core dump?

Step 1. Enable core dumps `ulimit -c unlimited -S`
Step 2. Start same app run `./AppRun`
Step 3. Print stacktrace `gdb $(pwd)/bin/xpiks core* -ex "thread apply all bt" -ex "set pagination 0" -batch` (probably will require to fix exact path to xpiks executable in the command)

Also if you will fail with `gdb` stacktrace chances are Xpiks has written it's own stacktraces to `~/.local/share/xpiks/` (search for `crashes/` directory)

**Comment by hybroid** [comment]
~/.local/share/Xpiks/Xpiks/crashes is empty.

My GDB was crashed with this core dump :'( Log:
```
[hybroid@lip squashfs-root]$ ./Xpiks
QFSFileEngine::open: No file name specified
Аварийный останов (стек памяти сброшен на диск)
[hybroid@lip squashfs-root]$ gdb $(pwd)/Xpiks core.2336 -ex "thread apply all bt" -ex "set pagination 0" -batch
[New LWP 2336]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
symfile.c:891: internal-error: sect_index_text not initialized
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) [answered Y; input not from terminal]

This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.

symfile.c:891: internal-error: sect_index_text not initialized
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? (y or n) [answered Y; input not from terminal]
Аварийный останов (стек памяти сброшен на диск)
```
Coredump in attach.
[core.2336.gz](https://github.com/ribtoks/xpiks/files/3015691/core.2336.gz)

**Comment by ribtoks** [comment]
Well, then there's no much I can help you with. Probably the problem is with stability of your current Arch system.

**Comment by hybroid** [comment]
Most likely the problem is that binary packages are a pain in the ass.
