### ISSUE TITLE
Fail when try to add dictionary

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#640]
System info: Ubuntu 16.04 amd64, Xpiks 1.5.2.2 (Appimage).

When I'm trying to add dictionary (in my case from directory "/usr/share/stardict/dic") there is nothing happening, dictionary list is empty as before.

Unfortunately there is no way to copy logs from "Logs" window (#639), and there is no easy way to copy text directly from log file (is it encrypted?), so I'm attaching screenshot:
![xpiks-log-screenshot](https://user-images.githubusercontent.com/17202099/56267116-90425b80-60f6-11e9-9e54-15c6ef654777.png)

**Comment by ribtoks** [comment]
Hi

You can see from logs that Xpiks cannot find .idx and .ifo files. Xpiks does not support .dz files. There's nothing really I can do. Xpiks support of dictionaries is based on [ssdll library](https://github.com/ribtoks/ssdll)
