### ISSUE TITLE
Zero sized each image in info panel

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#641]
System info: Ubuntu 16.04 amd64, Xpiks 1.5.2.2 (Appimage).

Screenshot:
![xpiks-info-zero-filesize](https://user-images.githubusercontent.com/17202099/56267649-1d39e480-60f8-11e9-81f9-ff86408aa536.png)

**Comment by ribtoks** [comment]
Thanks for reporting, this is a bug. Are you able to reproduce it with same file?

**Comment by zhartus** [comment]
> Are you able to reproduce it with same file?

No, unfortunately. I just reopen application and now it seems ok, it shows real file size for same files.
