### ISSUE TITLE
Reordering keywords not only in "single editing view" or "batch editing view", but in "main view" too

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#646]
Is it possible?
I know about [limitations](https://xpiksapp.com/tutorials/howto-reorder-keywords/) for now, but maybe in future versions?

**Comment by ribtoks** [comment]
Main list of artworks is overloaded with features, labels and UI elements. I'm thinking if it makes sense to remove it altogether. Adding even more features there is not worthwhile in my opinion.
