### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#651]
It would be convenient to see tooltips when hovering on non-obvious elements. You can also write hotkeys for actions for which they are available (in the manner that is already done in the menu).

**Comment by ribtoks** [comment]
Please define what is "non-obvious" for ~60 000 people (Xpiks downloads). On this scale there's nothing like "obvious". Only what people are used to and what they are not used to do. You can learn more about [existing hotkeys here](https://xpiksapp.com/tutorials/interface-hotkeys/). I'm closing this issue as it is too broad. Next time please be more specific.

**Comment by zhartus** [comment]
Well, apparently I really was not specific. Instead of "non-obvious elements" you can put "all buttons in application", or "all clickable elements". This approach is practiced in many applications, but of course you decide.
