### ISSUE TITLE
Remove duplicates directly from dialog “Show duplicates”

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#652]
It would be nice if you could remove duplicates directly from the dialog that appears by clicking on “Show duplicates”.

**Comment by ribtoks** [comment]
Maybe it would, maybe not. Currently the duplicates removal flow is like it is and I do not see (and you did not provide) any reasons for lots of additional work. So far you can remove duplicates from any editing view since Xpiks highlights them.
