### ISSUE TITLE
Add ability to add new keywords to the beginning of list or any other desired position

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#655]
Right now it's possible only with "Edit in plain text" option.

**Comment by ribtoks** [comment]
No, there're other ways to do that. Check out [this tutorial](https://xpiksapp.com/tutorials/howto-reorder-keywords/). Also keywords will be added only to the end of the list. There's no reason for user to choose a placement for the keyword before typing.

**Comment by zhartus** [comment]
> There's no reason for user to choose a placement for the keyword before typing.

Well, for many stocks, the order of the keywords matters — the most significant keywords should be at the top of the list.

And here is my real case in which I may need to add keywords to the top of the list:
It is convenient to first add all common words for all images in the list. Then I add keywords specific to each image, and these keywords are certainly more important than general ones. But by default they are added to the end of the list.
I understand that I can first write specific words for each image, and then add common words using group editing and a checkbox "Only append new keywords", but it's more convenient for me to act in a described order. Among other things, you can forget to check "Only append new keywords" and accidentally lose the results of long work.

In any case, the final decision is of course yours. I'm just trying to get my point across.
