### ISSUE TITLE
[site] Links to 404 pages in the "Tutorials" section

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#658]
In the “Tutorials” section on some pages (for example, at https://xpiksapp.com/tutorials/interface-upload/ ) there is a links like “read more about security”, which leads to the 404th page (apparently, the deleted blog post): https://xpiksapp.com/2016/01/13/ftp-and-security/

**Comment by zhartus** [comment]
By the way, here's a typo on this page: https://xpiksapp.com/tutorials/keywords-overview/
"simliest" instead "simpliest" (or "simplest").

**Comment by ribtoks** [comment]
Fixed both.
