### ISSUE TITLE
Quick cleaning of the folders list in the sidebar

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#660]
Sometimes it happens that you have to open a large number of directories and files, and they all accumulate in the sidebar. It also happens that you need to completely clear the sidebar (close all opened folders). Now for this you need to close each folder separately. It would be nice to have a button on the panel to clear all list at once.

**Comment by ribtoks** [comment]
To clean all files, just select "All" in the dropdown and press "Delete" button. This will remove all directories as well. You cannot remove directories and keep files open at the same time.

**Comment by zhartus** [comment]
Thank you
