### ISSUE TITLE
Button "retry all failed" from failed uploads

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#669]
Xpiks supports "read-only" view on failed uploads that is in `FailedUploadsArtworks.qml`. C++ models that is responsible for collection of this information is `UploadWatcher`.

This task is to improve this status quo in the "read-write" direction. Particularly a new button "Retry upload" should be added on the other side of "Close" button in failed uploads. Functionality should theoretically be in new method `ArtworksUploader::retryFailedUploads()` (or something along those lines) that will construct new artworks snapshot and select correct upload infos.

To construct upload infos one can use method `UploadInfoRepository::tryFindItemByHost()` where host will come from `UploadWatcher`.

**Comment by velmafia** [comment]
I'm working on it.

**Comment by ribtoks** [comment]
Implementation of this issue in incomplicated by the fact that `FtpCoordinator` from `libxpks` can only upload a single `ArtworksSnapshot` to all `UploadInfo`s, however, in this case it should be different snapshots to different `UploadInfo`s. Therefore, `libxpks` changes required.

**Comment by velmafia** [comment]
I prepared proposal for this issue: #758

As we agreed in email, I changed `libxpks_stub` and multi `ArtworksSnapshot` is now possible, at this moment real `libxpks` should be changed (to fix `AppVeyor`).

I also implemented integration test for this feature, but I have one problem:
Currently ftp directory (`src/xpiks-tests/ftp-for-tests`) is not cleared after every upload test, so checking if files are correctly uploaded may not work. I added `clearFtpDir()` function and I call it in `teardown()` method for "ftp upload tests", but in `travis-ci` file are not deleted, I don't know why (my solution working for me locally, and for `AppVeyor`). I added additional logs, with `[CLEAR-FTP]` tag (logs will deleted in finall PR). This files exist, but are some problem with their removal. Do you have idea where is problem?

**Comment by ribtoks** [comment]
Hi

Thanks, I’ll try to review PR tomorrow or Monday the latest.

The problem with files removal could be that you have to remove them Before your test, not after. So clearFTP() should be in the XpiksTestsApp::cleanup(). There’re other tests that upload something. Also it might fail on Travis, but succeed locally because of randomization. Let me know if that helps.



On Aug 17, 2019, at 13:17, Kamil Oborski <notifications@github.com<mailto:notifications@github.com>> wrote:

I prepared proposal for this issue: #758

As we agreed in email, I changed libxpks_stub and multi ArtworksSnapshot is now possible, at this moment real libxpks should be changed (to fix AppVeyor).

I also implemented integration test for this feature, but I have one problem:
Currently ftp directory (src/xpiks-tests/ftp-for-tests) is not cleared after every upload test, so checking if files are correctly uploaded may not work. I added clearFtpDir() function and I call it in teardown() method for "ftp upload tests", but in travis-ci file are not deleted, I don't know why (my solution working for me locally, and for AppVeyor). I added additional logs, with [CLEAR-FTP] tag (logs will deleted in finall PR). This files exist, but are some problem with their removal. Do you have idea where is problem?

**Comment by velmafia** [comment]
I found where is problem with files removal - `xpiks` bianry don't have permission to remove this file, binary user are not the same as file user:
```
16:12:58.358 info T#14707 clearFtpDir - [CLEAR-FTP] file: "/home/travis/build/velmafia/xpiks/src/xpiks-tests/ftp-for-tests/seagull.jpg" exist: true
16:12:58.358 info T#14707 clearFtpDir - [CLEAR-FTP] permision of file:  "/home/travis/build/velmafia/xpiks/src/xpiks-tests/ftp-for-tests/seagull.jpg" are QFlags(0x4|0x40|0x400|0x2000|0x4000)
16:12:58.358 info T#14707 clearFtpDir - [CLEAR-FTP]: username: "travis" file owner: "syslog"
16:12:58.358 info T#14707 clearFtpDir - [CLEAR-FTP] remove file:  "/home/travis/build/velmafia/xpiks/src/xpiks-tests/ftp-for-tests/seagull.jpg" status: false
```
~Can we change this permission (or ftp files owner)?~
I will change this permission in `xpiksftp` docker configuration.

**Comment by ribtoks** [comment]
Fixed in libxpks as well.
