### ISSUE TITLE
Warnings about containing keywords in description and title — are they really needed?

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#682]
Every time I upload each image I get the same warnings:
> Description contains some of the keywords
> Title contains some of the keywords

I understand that these warnings are intentionally displayed and that this is not a bug, but I do not understand why they are needed.

The presence of keywords in the title and description — this is natural, isn't it? 
I think that on the contrary, it is strange to make a title and description without the participation of keywords. Moreover, it is rather difficult not to do this. For example, if a cat is shown in the picture, and the word “cat” is added to keywords, how can you not mention this word in the title and description?
By the way, I constantly receive these warnings in Xpiks, but at the same time I have never had a problem with this on any of stocks.

If, however, these warnings are for some reason needed by someone, maybe it makes sense to give users the ability to turn them off in the settings?

**Comment by ribtoks** [comment]
Shutterstock removes keywords that are present in Description. This is where this warning originated from. Yes, it makes sense to turn them off. This is kind of included in issue #336 (Ability to customize detected warnings)

**Comment by zhartus** [comment]
> Shutterstock removes keywords that are present in Description.

This is strange because Shutterstock doesn't remove any my keywords that are present in description. And I just checked for others (not my) illustrations - the same thing, their descriptions contains keywords.

**Comment by ribtoks** [comment]
It was definitely the case in past. Maybe they changed this behavior. But indeed - these are not the most obvious warnings. Probably I can remove them.
