### ISSUE TITLE
Disable "Replace" button if nothing is selected in spell suggestions

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#688]

**Comment by velmafia** [comment]
`Replace` button is enabled when nothing is selected only after `Reset All` button. This is what you meant when you write this issue?

**Comment by ribtoks** [comment]
Current behavior is that when you have spelling errors and you open 'Fix spelling' dialog, "Replace" button is enabled even though you cannot replace anything (because you didn't select anything). Desired behavior is that replace button property "enabled" is bound so some property of the `spellCheckSuggestionModel`. And in it's own turn model will fire signal only when user clicked on something. Getter of the property will check if there's anything selected in any of `m_SuggestionsList`

**Comment by ribtoks** [comment]
Yeah.. Apparently I have implemented this in past and forgot to close the issue. Sorry.

Also - I forgot to do it in `Reset All` so your comment is 100% valid. Let's consider this as the task then.

**Comment by ribtoks** [comment]
Let's merge your change to master before 1.5.3 branching.
