### ISSUE TITLE
Create switch to disable legacy backups cleanup

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#691]
Start legacy backups cleanup MaintenanceTask only if the appropriate switch is ON.
To create a switch see an example of anything existing in `SwitcherModel` (basically you need to copy-paste few lines of code in `SwitcherConfig` for declaration and parsing and pass-through it as a method in `SwitcherModel`)

**Comment by velmafia** [comment]
I'm working on it.

editing `switches.json` in branch `gh-pages` is also in scope in this task?

What should be default value of this switch: `legacy backups cleanup` enabled or disabled?

**Comment by ribtoks** [comment]
Default value should be `disabled` (it will be disabled for all newer Xpiks releases like 1.6+ since "old backups" is a thing from past).

If it's not hard, yes, you can update `switches-153.json` as well.
