### ISSUE TITLE
Improve open files/folders startup directory experience

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#718]
Follow up from a [user request](https://groups.google.com/forum/#!topic/xpiks-support/WDS36n51Jx0).

Currently "Open file" and "Open directory" dialogs start in `folder: shortcuts.pictures`. This leads to non-optimal experience when opening deeply nested files (need to go every time to the bottom of hierarchy). This task is to add method `QUrl UIManager::getOpenDialogStartupCandidate(QUrl default)` or similar to `UIManager` that will return last open directory in Xpiks. `RecentDirectoriesModel` can help with that - it needs to be added as a dependency to UIManager ot something along those lines.

**Comment by velmafia** [comment]
I coded what you write above, but during the tests I found that this is already implemented [here](https://github.com/ribtoks/xpiks/blob/46917f21d5b4364e36a2277a6d8584c65ab8e02b/src/xpiks-qt/main.qml#L996):
```
var latestDir = recentDirectories.getLatestItem()
chooseArtworksDialog.folder = latestDir
chooseDirectoryDialog.folder = latestDir
```

**Comment by ribtoks** [comment]
Yeah, let's park it for now. I'll reach back to the user.

**Comment by ribtoks** [comment]
Yeah, let's park it for now. I'll reach back to the user to ask why it wasn't working.

**Comment by ribtoks** [comment]
Thanks for the investigation!

**Comment by ribtoks** [comment]
I proposed user to use Favorites feature in their file manager and user agreed. So far we can consider this issue as "irrelevant" anymore.

**Comment by velmafia** [comment]
User was right. problem still exist before first `onArtworksAdded`, after that everything works well.
I don't know why this was working when I tested it before.

@ribtoks please, reopen this issue. I will fix this.

**Comment by ribtoks** [comment]
@velmafia  There's no need to fix this:

- if we have "restore last session" ON then we will set filedialog path anyway because of `onArtworksAdded`
- if we have "restore last session" OFF which directory you will set as default and why? This is a tricky question without right answer.

**Comment by velmafia** [comment]
@ribtoks "restore last session" is working only when you left opened directory in `xpiks` before exit. If you close all directories `Add directory` will always start in `shortcuts.pictures`. In my mode of work I always close all directories before I close `xpiks`. Maybe user who requested this feature does the same.

What I propose is the same what was in scope on this issue: [proposal](https://github.com/velmafia/xpiks/commit/958a5a76b0f657ffdef7f7ce111b477af32be6eb).

**Comment by ribtoks** [comment]
@velmafia I understand what you proposed even from your comment. What I'm saying is that it's hard to conclude that startup directory in case when 'restore last session' is OFF should be most recent directory. What if next time user opens Xpiks will be in a week? I will not be interested in my previous directory. What if user already moved directory that was recent last time? There will be many cases like that. If we set last directory only for current session, this is much more reliable given that with 'restore last session' it will 'automatically' work.

**Comment by velmafia** [comment]
Maybe I'm little stubborn, but for me behaviour when default path for "Add directory" depends on whether last time I closed the working directory or not, isn't fully intuitive (as we see for user who start this issue also). 

If startup directory is problematic when 'restore last session' is OFF, so maybe we can check this? In my proposal this will be really easy `UIManager` already has `SettingsModel`, so it's need one `if` only.  

Then:
- if "restore last session" is ON, always use recent last directory (if exist), no matter if you close working directory last time, or not. 
- if "restore last session" is OFF, leave `xpiks` behaviour as is now.

For me this will be more clear and intuitive solution. But it's your decision, I just presents my POV.

**Comment by ribtoks** [comment]
@velmafia ok, last described algorithm makes sense

**Comment by velmafia** [comment]
OK, I will do this.

**Comment by velmafia** [comment]
> I don't know why this was working when I tested it before.

Finally I found where was problem. I have 2 laptop where I develop `xpiks`, on first I have `qt` installed from Debian repository (`apt install qt5-default`), on second installed by official installer (`Qt Online Installer for Linux`), in both case version was the same (5.11.3).

And know:
- when I use `qt` from Debian repo - everything working as expected;
- when I use `qt` from official installer - `Open File/Directory` is always opened in last directory, even if I close `xpisk`, remove whole`~/.local/share/Xpiks/`, remove build cache (`git clean -fdx`), and change branch :/

Maybe this is related with different location of some cache files, but after removing `~/.local/share/Xpiks/` `Terms and conditions` was appeared, so `xpiks` configs was deleted.
