### ISSUE TITLE
Build tiny-AES as a library

### ISSUE THREAD

**Issue by velmafia** [ribtoks/xpiks#728]
Build `tiny-AES` as library (currently is being built together with `xpiks`)

**Comment by ribtoks** [comment]
No need to do it. With latest tiny-aes I was able to remove rename step. It's absolutely fine to build as part of Xpiks.

**Comment by velmafia** [comment]
I already done [this task](https://github.com/velmafia/xpiks/commits/dirty/tiny-aes), but not yet prepare clean version for PR. :)

**Comment by velmafia** [comment]
I make this during #729, and I forgot update status on GitHub. But OK, this no real profit, and was fast and easy task, so we can drop it.
