### ISSUE TITLE
Terms and conditions: imposible to Agree

### ISSUE THREAD

**Issue by velmafia** [ribtoks/xpiks#732]
Hi,
after first run when `Terms and conditions` window is displayed, is impossible to click `Agree` and close the windows, only `Disagree` close the windows (and `xpisk` for release build).

branch: current master (debug and release build)
logs: [terms-and-conditions.log](https://github.com/ribtoks/xpiks/files/3343011/terms-and-conditions.log)

![terms-and-conditions](https://user-images.githubusercontent.com/5277222/60398399-ba34e700-9b57-11e9-8c58-a7896a4e8335.gif)

**Comment by ribtoks** [comment]
@velmafia can you check if it works for tag [v1.5.3] (i.e. last "official" release)?

**Comment by velmafia** [comment]
@ribtoks: tag [v1.5.3] works well. So "official" release isn't affected.
