### ISSUE TITLE
Support plugin installation from archive

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#751]
part of #445 effort

Currently you can only install a plugin by providing a `.dll` or `.dylib` or `.so` (see `PluginManager::addPlugin()` codepath). Actually it will be nice to hide these details from user and ship plugins with `.xpiksplugin` extension (or _anything_ along those lines) which actually will be a zip archive.

This task is to enable such functionality by adding 1 additional steps to `PluginManager::addPlugin()` (or one of the internal functions) that will unzip plugin to some temporary directory and install from there (with proper error handling etc.).

Also it will be required to modify integration test for `xpiks-hello-world` plugin that is currently being installed without zip archive.

Xpiks should **always** save plugin archive ("raw") to some additional directory like `.../plugins/packages/`.

**Comment by velmafia** [comment]
I'm working on it.
