### ISSUE TITLE
Save installed plugins metadata to json

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#752]
part of #445 effort

Right now information about installed plugins is kept only in memory.

This task is about adding a json config (e.g. like `SettingsModel` has) to `PluginManager` class that will save useful plugin information in there. Useful plugin information is, but not limited to:
* filepath to installed plugin
* filepath to "raw" plugin package (from #751)
* installed version
* name
* enabled/disabled state
* sha1 sum of the main file (`.dll` etc.)
* last successful load date
* anything else?

Json file should be saved on every qualifying change (e.g. added/removed plugin, enabled/disabled plugin). This should be implemented same way as `SettingsModel` and others using `DelayedActionEntity` class and `justChanged()` API.

Also `PluginManager` should load json on load (or in some new method `PluginManager::initialize()` etc.) called from `XpiksApp::initialize` where all entities load json configs.

This task is only about adding such config. Actual usage of it (loading plugins comes as a separate task).

Also need to clear this config for integration tests in `::cleanup()` method between runs.

Plugin json config should be handled by a completely separate new class (like `PluginsConfig`) that will be a member of `PluginsManager`.

**Comment by velmafia** [comment]
I take this task.
