### ISSUE TITLE
Optimize artworks filtering logic in filterAcceptsRow() function

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#764]
Currently every `FilteredArtworksListModel::filterAcceptsRow()` call evaluates search query on every call in `Helpers::hasSearchMatch()`. 

This task is about creating a new class `PreparedFilter` in `filteredartworkslistmodel.h` that will encapsulate `FilteredArtworksListModel::m_SearchTerm` inside and will evaluate filter (parse it to some new flags) in `FilteredArtworksListModel::setSearchTerm()` and in `::filterAcceptsRow()` it will only call `m_PreparedFilter.hasMatch()` instead of `Helpers::hasSearchMatch()`. 

`PreparedFilter::setSearchTerm()` will encapsulate `SearchFlags` and `m_SearchTerm` from `FilteredArtworksListModel` and will be called from `FilteredArtworksListModel::setSearchTerm()` instead of `m_SearchTerm = value`;

**Comment by vleschuk** [comment]
I'm on it.

**Comment by ribtoks** [comment]
Resolved in bcdc629c901a03814e539100073ceeda20b854b7
