### ISSUE TITLE
cppcheck is broken on Travis CI

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#768]
cppcheck always crashes in Travis. Possible fix would be to update it (e.g. to 1.89) or simply remove it altogether since it doesn't bring any value.

**Comment by velmafia** [comment]
Problem is related with old Ubuntu verison, maybe we can update Ubuntu on travis ([Xenial or Bionic)](https://docs.travis-ci.com/user/reference/overview/#linux)?
