### ISSUE TITLE
Strange (irrelevant) Shutterstock search vectors results for keywords suggestion

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#776]
Xpiks 1.5.4.2, Ubuntu 19.04.

As far as I know, it's normal that suggested Shutterstock vectors for keywords suggestion doesn't match regular Shutterstock search due to different search algorithms on Shutterstock site and in Xpiks. But even considering this fact there are some strange results in suggested Shutterstock vectors list in last Xpiks version. For almost every request, most of the results are occupied by the same type of images, on the basis of which it is difficult to select the relevant options. It is difficult to explain in words, but it can be clearly seen in the attached screenshots. In many cases, the results are completely irrelevant (as "car" and "flower" examples).

![xpiks-shutterstock-search-problem-01](https://user-images.githubusercontent.com/17202099/66134285-c457fd00-e600-11e9-9aa1-f83d662aed92.jpg)
![xpiks-shutterstock-search-problem-02](https://user-images.githubusercontent.com/17202099/66134286-c4f09380-e600-11e9-9636-808814e37423.jpg)
![xpiks-shutterstock-search-problem-03](https://user-images.githubusercontent.com/17202099/66134287-c4f09380-e600-11e9-80d7-1bb104177b07.jpg)
![xpiks-shutterstock-search-problem-04](https://user-images.githubusercontent.com/17202099/66134288-c4f09380-e600-11e9-8ecd-d0b5b1fa25bd.jpg)
![xpiks-shutterstock-search-problem-05](https://user-images.githubusercontent.com/17202099/66134290-c5892a00-e600-11e9-9169-3ee4187839ad.jpg)

**Comment by ribtoks** [comment]
Unfortunately there's no way for Xpiks to alter how Shutterstock provides Xpiks with search results. I suggest you using Adobe Stock search provider that does not limit results.

**Comment by zhartus** [comment]
Well, the search results on the Shutterstock site are completely normal. Until recently, they were normal in Xpiks too, but then apparently something broke.

**Comment by ribtoks** [comment]
@zhartus I already explained somewhere that Shutterstock now provides different search results for 3rd party applications. There's nothing to do here with "breaking" something.
