### ISSUE TITLE
[feature request] Delete keyword(s) in batch of images (in edit dialog)

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#777]
We have the opportunity to add new keywords at once to several selected images, but there is no such possibility for deletion. That is, if a user, for example, accidentally adds an unnecessary keyword to all images, and then wants to delete it, then he will have to delete it for each image separately. Or is there a simpler way?

**Comment by ribtoks** [comment]
Such opportunity exists https://xpiksapp.com/tutorials/howto-delete-keywords/
