### ISSUE TITLE
Easy "check for updates" system

### ISSUE THREAD

**Issue by Ribtoks** [Ribtoks/xpiks#78]
Implement super-simple updates checking which will silently notify user about new updates and provides a download link.
Check latest release at GitHub etc. - download smth like json with update_available yes/no + update link if applicable.
This functionality should be configurable (enabled/disabled) from Settings and displayed as green link in status bar on the left (near logs)

**Comment by Artiom-M** [comment]
For debian this functionnality should be disabled as it has it's own release check integrated to the packaging system. So it should be possible to disable it at compile time as well.
