### ISSUE TITLE
Xpiks 1.5.5 doesn't start on Ubuntu ("no Qt platform plugin could be initialized")

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#787]
Ubuntu 19.10 amd64, Xpiks 1.5.5 (AppImage).

Xpiks 1.5.5 even doesn't start.
When starting from the console, I get an error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

The previous version (1.5.4) is working fine.

**Comment by ribtoks** [comment]
@zhartus Thanks for reporting this problem. I fixed the package, please download it again from the website.

**Comment by zhartus** [comment]
@ribtoks It works now, thanks.
