### ISSUE TITLE
Build helloworld plugin from vendors in `build_vendors_xxx` scripts for local testing

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#796]
Currently helloworld plugin is only build in TravisCI or AppVeyor. Need to build it as part of build_vendors_xxx scripts so integrations tests could be run locally without problems

**Comment by ribtoks** [comment]
@velmafia This one would be great to do for local environment setup

**Comment by velmafia** [comment]
I take this task.

`helloworld` submodule should also be moved to `vendors`? Currently is `src/xpiks-tests/plugins-for-tests/helloworld`

**Comment by ribtoks** [comment]
@velmafia Technically it's not a vendor part since it's not a part of Xpiks itself. But you think it's better, I don't have any objections.

**Comment by velmafia** [comment]
OK, so I move it.   
(From my POV better destination name would be `third part`, or something like it, but if we use `vendors` so I move it there. Especially if this plugin will be build together with `vendors`).

----
One more question:
helloworld plugin has different `INCLUDEPATH` / `SOURCES` path for `travic-ci` and `appveyor`, and different of everything else. Do you use this project somewhere else? (Now  this paths should be the same for `CI` and `not CI` build to be useful for local build.)

**Comment by ribtoks** [comment]
The only problem with moving is that "moving submodules in git is complicated", but if you assure me that after I do `git pull` and `git submodule update --init` everything will be great - go on and move it.

Hello-world plugin currently is a showcase of all plugin capabilities. I don't use it, it's more like "alive documentation". You can probably remove these different `INCLUDEPATH` **and** `DESTDIR` settings. (removing destdir, since plugins now install from archive, and these destdir tricks were only for local development)

**Comment by velmafia** [comment]
Changes in plugin is required to solve this issue: https://github.com/ribtoks/xpiks-helloworld-plugin/pull/2

**Comment by ribtoks** [comment]
@velmafia Merged
