### ISSUE TITLE
Unable to close About dialog

### ISSUE THREAD

**Issue by Artiom-M** [Ribtoks/xpiks#86]
On debian about dialog has no close button for some reason.
![screenshot from 2015-07-22 14 56 06](https://cloud.githubusercontent.com/assets/4058815/8825771/d7b74862-3081-11e5-894f-edc8b3a6013c.png)

**Comment by Ribtoks** [comment]
Does settings dialog has one?

**Comment by Ribtoks** [comment]
If you're using Gtk3, then this issue is not valid, because there're a lot of issues in qt5-gtk3 package.

**Comment by Artiom-M** [comment]
Yes in settings dialog all is ok. In upload dialog as well.

**Comment by Ribtoks** [comment]
Upload dialog is a dialog implemented by QML panels. Only About and Settings are dialogs implemented as separate Windows. You can check by yourself that both About and Settings use _flags: Qt.Tool_ so if they behave differently, there's an issue in some debian's Qt package.

**Comment by Artiom-M** [comment]
Or may be there is no Close button for About window. This is the main difference I see between it and Settings window.

**Comment by Ribtoks** [comment]
*Artiom-M*, please take a look at qml files for SettingsWindow and AboutWindow in directory /Dialogs/.
The only difference is size of the window. They both use http://doc.qt.io/qt-5/qt.html#WindowType-enum _Qt.Tool_ flag. There's an error in some debian qt package. About dialog has close button in Windows and in OS X.

**Comment by Artiom-M** [comment]
That's strange because in SettingsWindow file there is 
>                StyledButton {
>                    text: qsTr("Exit")
Have a look at this commit, fixing the issue for me:
https://github.com/Artiom-M/xpiks/commit/04167599807c7bb5915ae24e9c619efbccf5c964

**Comment by Ribtoks** [comment]
_Artiom-M_, both dialogs should have a header with default close button of the operating system you're using. In case you use Gtk3, there're a lot of issues, but just missing border. 
So what DE are you using?
Also About and Settings dialogs should appear in the screen center. Do you observe such a behavior? Or they appear in the topleft corner?

**Comment by Artiom-M** [comment]
I have Gnome and GTK3. Yes they appear in the corner, but it is not a big issue. While About dialog is modal and without close button it blocks the application.
Both windows have borders, and a window menu in the header, but "Close" option is inactive and there is no "x" button on it. 
As I understand it is expected behavior for a "Tool" window. 
By the way there is a "Close" button for the settings window, why not to add it to the "About" window?

**Comment by Ribtoks** [comment]
Exit button for the settings window exists because it acts like "Cancel" button (it also as "Save" button). About dialog does not have any action. I will add a behavior when you click on About dialog body it will close itself (like implemented in various software e.g. Skype).

_Artiom-M_, Xpiks will have tons of issues in GTK3 environment. It's not usable there. It will draw itself over the screensaver and have other glitches.

**Comment by Artiom-M** [comment]
Just an observation. If I change Qt.Tool to Qt.Dialog the window is correctly positioned in the middle of the window.

**Comment by Ribtoks** [comment]
Cool, thanks! Just pushed suggested edits.
