### ISSUE TITLE
Copy keywords function is confusing

### ISSUE THREAD

**Issue by Artiom-M** [Ribtoks/xpiks#87]
Copy keywords function is confusing. There is no "Paste keywords" button. 
I propose to change it's function. It should copy (append) all keywords from current image to all selected images.

**Comment by Ribtoks** [comment]
Copy keywords is a compatibility feature like some stocks have so microstockers which are used to it will find it in Xpiks too. You can paste keywords with Ctrl-V/Cmd-V and mouse, but you can't select keywords with mouse and copy them with Ctrl-C. That's why _Copy keywords_ exists, while _Paste keywords_ doesn't.

**Comment by Artiom-M** [comment]
So what about to add this function? The ability to duplicate keywords from current image to all selected images.

**Comment by Ribtoks** [comment]
You have this ability using Multiple Edit feature. Where do you propose to add this? The only was I see it - we can add small context menu under the keywords and put it there along with some other actions.

**Comment by Artiom-M** [comment]
Ah, I see what do you mean as "Multiple Edit": select images, than press "Edit" button. This is exactly what is needed in cooperation with Copy/Paste keywords. 
Anyway "Paste Keywords" along with "Copy Keywords" would be more consistent.

**Comment by Ribtoks** [comment]
Ok, you can make a context menu under the keywords of each image with caption (More actions *arrow-down*). This menu can contain "Append keywords to all images" and "More edits" (which is also accessible by double-click on an image).
