### ISSUE TITLE
Show number of uploaded images in upload progress

### ISSUE THREAD

**Issue by Artiom-M** [Ribtoks/xpiks#95]
It would be good to know during upload process the number of already uploaded images.
I think it should print on the progress bar the numbers: uploaded / total

**Comment by Ribtoks** [comment]
It makes no sense if we're uploading items to several hosts since upload process is parallel. Overall progress is illustrated by progress bar and is quite sufficient. What we can do more is just to show percentage, but it's not that much crucial.

**Comment by Artiom-M** [comment]
So why not to show per host progress? During upload write this on each selected line in the hosts config.
![upl](https://cloud.githubusercontent.com/assets/4058815/9172541/88b6de42-3f74-11e5-807e-fe2f9f17d95f.png)
Sometimes upload to some hosts can stuck and it's good to know that on others all is uploaded and to see which one is stuck.

**Comment by Ribtoks** [comment]
Well, at first I wanted to do the same (Stock Submitter looks like this), but UI looks overfilled with numbers. Also, it's quite a big amount of work to implement this, so I implemented just overall stats. If you're up to implementing this, take a look into ArtworkUploader, UploadCoordinator and UploadWorder classes.
